In [325]:
import numpy as np
import pandas as pd

In [326]:
dataSetPath = 'KMC_student_dataset.xlsx'

In [327]:
# read the excel using pandas data frame
dataFrame = pd.read_excel(dataSetPath)
print(dataFrame)

    Study Hours  Sleep Hours  Attendance Percentage  Exercise Hours   SSC GPA  \
0             7            7                     63               4  4.134026   
1             4            7                     66               4  4.370527   
2             8            4                     85               1  3.817880   
3             5            6                     99               6  4.778903   
4             7            8                     89               4  3.953231   
5             3            6                     53               1  4.744879   
6             7            8                     51               0  4.550116   
7             8            4                     55               3  3.348352   
8             5            5                     91               3  2.286230   
9             4            7                     53               3  3.112455   
10            8            4                     78               4  4.006524   
11            8            7

In [328]:
# convert dataframe to array using numpy
dataArray = np.array(dataFrame)
# converting all elements to float
dataArray = dataArray.astype(float)
print(dataArray)

[[ 7.          7.         63.          4.          4.13402586  2.60515761]
 [ 4.          7.         66.          4.          4.37052662  4.68729079]
 [ 8.          4.         85.          1.          3.81787992  3.42611067]
 [ 5.          6.         99.          6.          4.77890264  3.68982672]
 [ 7.          8.         89.          4.          3.95323108  4.08654826]
 [ 3.          6.         53.          1.          4.74487903  2.41799436]
 [ 7.          8.         51.          0.          4.55011573  3.81325214]
 [ 8.          4.         55.          3.          3.34835202  3.61952327]
 [ 5.          5.         91.          3.          2.28623035  2.60918367]
 [ 4.          7.         53.          3.          3.11245476  4.82856071]
 [ 8.          4.         78.          4.          4.00652376  3.7965964 ]
 [ 8.          7.         67.          0.          3.99776707  4.0843548 ]
 [ 3.          9.         75.          4.          3.77389336  4.64140352]
 [ 6.          5.        

In [329]:
# let us create another table for normalized array | elements initially 0
normalizedArray = np.zeros_like(dataArray)
print(normalizedArray)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [330]:
# get no of rows and cols
print(normalizedArray.shape)
noOfRows = normalizedArray.shape[0]
noOfCols = normalizedArray.shape[1]

(25, 6)


In [331]:
# normalized data means converting the elements between 0 to 1 considering others
# normalized_x = (x - min) / (max - min)
# dataArray[:, col] = an array of all rows where column = col
# store the normalize data
for col in range(noOfCols):
  colMin = np.min( dataArray[:, col] ) # minimum element of the col
  colMax = np.max( dataArray[:, col] ) # maximum element of the col
  normalizedArray[:, col] = (dataArray[:, col]- colMin) / (colMax - colMin)

print(normalizedArray)

[[0.75       0.6        0.25       0.66666667 0.72041646 0.11491476]
 [0.375      0.6        0.3125     0.66666667 0.80506738 0.94376372]
 [0.875      0.         0.70833333 0.16666667 0.60725807 0.44171714]
 [0.5        0.4        1.         1.         0.95123777 0.54669639]
 [0.75       0.8        0.79166667 0.66666667 0.65570442 0.70462204]
 [0.25       0.4        0.04166667 0.16666667 0.93905967 0.04040941]
 [0.75       0.8        0.         0.         0.86934787 0.59582919]
 [0.875      0.         0.08333333 0.5        0.43919953 0.51871022]
 [0.5        0.2        0.83333333 0.5        0.05903339 0.11651744]
 [0.375      0.6        0.04166667 0.5        0.35476462 1.        ]
 [0.875      0.         0.5625     0.66666667 0.67477952 0.58919893]
 [0.875      0.6        0.33333333 0.         0.67164523 0.70374888]
 [0.25       1.         0.5        0.66666667 0.59151392 0.92549706]
 [0.625      0.2        0.875      1.         0.25157695 0.61963817]
 [0.5        0.2        0.66666667

In [332]:
# randomly select 3 centroids
k = 3
noOfPoints = normalizedArray.shape[0] # rows
randomPoints = np.random.choice(noOfPoints, k, replace=False) # replace = false | we don't want same array twice
print("random points:")
print(randomPoints)

centroids = normalizedArray[randomPoints]
print("centroids:")
print(centroids)

random points:
[23  0 13]
centroids:
[[0.         0.8        0.4375     0.33333333 0.07565646 0.95697769]
 [0.75       0.6        0.25       0.66666667 0.72041646 0.11491476]
 [0.625      0.2        0.875      1.         0.25157695 0.61963817]]


In [333]:
distances = np.zeros(shape=(noOfRows, k))

for i in range(k):
  distances[:, i] = np.sum( abs(normalizedArray-centroids[i]), axis=1 ) # axis=1 means sum of same rows elements

print(distances)

[[2.95765627 0.         2.45689625]
 [1.77595824 1.35099989 2.42344932]
 [3.15936216 2.12329411 1.98360214]
 [3.41502928 2.19593628 1.2226026 ]
 [2.26990362 1.39608598 1.63077802]
 [2.9924715  1.70148189 3.50837815]
 [2.67567325 1.74651251 3.2415799 ]
 [2.99764388 1.74334572 2.0302172 ]
 [2.51958332 2.06298575 1.36233095]
 [1.45963047 2.00073708 2.46688284]
 [3.10023516 1.55742111 1.54947515]
 [2.36171759 1.51260535 2.69584566]
 [1.39317143 2.08948484 2.5291292 ]
 [2.84242668 2.45689625 0.        ]
 [2.87599271 1.3399969  1.36689936]
 [2.77825467 2.44256445 3.14416132]
 [3.54126487 2.23389182 2.36550485]
 [3.09374426 0.826026   2.32631757]
 [2.46646738 2.31349708 2.4990407 ]
 [1.71661375 2.94937586 1.95914627]
 [1.38484331 1.57281296 2.50747655]
 [2.81698412 1.39884785 2.00139842]
 [2.68899125 0.76866502 2.8548979 ]
 [0.         2.95765627 2.84242668]
 [2.44815608 2.28450019 2.2557294 ]]


In [334]:
clusters = np.argmin(distances, axis=1)
print(clusters)


[1 1 2 2 1 1 1 1 2 0 2 1 0 2 1 1 1 1 1 0 0 1 1 0 2]


In [335]:
newCentroids = np.zeros_like(centroids)
for i in range(len(centroids)):
  points = normalizedArray[ i==clusters ]
  # print(f'** {points} **')
  newCentroids[i] = points.mean(axis=0)

print(newCentroids)


[[0.225      0.72       0.44166667 0.4        0.29269271 0.81453775]
 [0.60714286 0.45714286 0.32738095 0.4047619  0.66763193 0.36385241]
 [0.60416667 0.2        0.79513889 0.55555556 0.49537078 0.41879537]]


In [336]:
# assigement-2
# apply K-Means Clustering
print(f'initial centroid: {centroids}')

iteration = 0
while not np.array_equal(centroids, newCentroids):
    
    # keeping track of previous centroids
    centroids = newCentroids

    distances = np.zeros(shape=(noOfRows, k))
    for i in range(k):
        distances[:, i] = np.sum( abs(normalizedArray - centroids[i]), axis=1 ) # axis=1 means row-wise sum

    # assign clusters based on minimum distance in betwwen
    clusters = np.argmin(distances, axis=1)

    # update centroids based on mean of points in each cluster
    newCentroids = np.zeros_like(centroids)
    for i in range(k):
        points = normalizedArray[clusters == i]  # points belonging to the current cluster
        if points.size > 0:  # avoid division by zero
            newCentroids[i] = points.mean(axis=0)

    iteration += 1
    print(f"Iteration {iteration}: Updated centroids")
    print(newCentroids)

print(f'final centroid: {centroids}')

initial centroid: [[0.         0.8        0.4375     0.33333333 0.07565646 0.95697769]
 [0.75       0.6        0.25       0.66666667 0.72041646 0.11491476]
 [0.625      0.2        0.875      1.         0.25157695 0.61963817]]
Iteration 1: Updated centroids
[[0.25       0.7        0.42013889 0.44444444 0.37808849 0.83607541]
 [0.56944444 0.51111111 0.22453704 0.35185185 0.65418155 0.25339382]
 [0.6625     0.24       0.70208333 0.51666667 0.56263704 0.43823978]]
Iteration 2: Updated centroids
[[0.25       0.7        0.42013889 0.44444444 0.37808849 0.83607541]
 [0.625      0.55       0.17708333 0.39583333 0.64450793 0.23864   ]
 [0.61363636 0.23636364 0.69318182 0.46969697 0.57799463 0.43216566]]
Iteration 3: Updated centroids
[[0.25       0.7        0.42013889 0.44444444 0.37808849 0.83607541]
 [0.625      0.55       0.17708333 0.39583333 0.64450793 0.23864   ]
 [0.61363636 0.23636364 0.69318182 0.46969697 0.57799463 0.43216566]]
final centroid: [[0.25       0.7        0.42013889 0.4444