In [80]:
import numpy as np
import pandas as pd

In [81]:
dataset1Link = '/content/drive/MyDrive/Class Contents/5. Summer 2024/AI Lab/Class Materials For The Students/Week 6/dataset1.xlsx'

In [82]:
dataframe = pd.read_excel(dataset1Link)
print(dataframe)

    SN  Study Hours  Attendance  Home Works Done  Papers Read  Total Marks  \
0    1          8.0          90                9            4        850.0   
1    2          7.0          99                9            3        797.5   
2    3          9.0          85               10            5        937.5   
3    4          7.5          86                8            4        802.5   
4    5          8.5          92                8            3        792.5   
5    6          6.0          65                6            2        562.5   
6    7          5.0          73                6            2        557.5   
7    8          5.5          80                6            1        537.5   
8    9          5.0          60                6            2        525.0   
9   10          4.5          62                6            2        517.5   
10  11          2.0          45                2            1        262.5   
11  12          3.0          35                2            1   

In [83]:
dataset = dataframe.to_numpy()

In [84]:
print(dataset)

[[1 8.0 90 9 4 850.0 'High']
 [2 7.0 99 9 3 797.5 'High']
 [3 9.0 85 10 5 937.5 'High']
 [4 7.5 86 8 4 802.5 'High']
 [5 8.5 92 8 3 792.5 'High']
 [6 6.0 65 6 2 562.5 'Medium']
 [7 5.0 73 6 2 557.5 'Medium']
 [8 5.5 80 6 1 537.5 'Medium']
 [9 5.0 60 6 2 525.0 'Medium']
 [10 4.5 62 6 2 517.5 'Medium']
 [11 2.0 45 2 1 262.5 'Low']
 [12 3.0 35 2 1 262.5 'Low']
 [13 2.5 33 1 1 220.0 'Low']
 [14 1.0 46 1 0 165.0 'Low']
 [15 2.0 58 2 0 245.0 'Low']]


In [85]:
y = dataset[0:15,5]
print(y)

[850.0 797.5 937.5 802.5 792.5 562.5 557.5 537.5 525.0 517.5 262.5 262.5
 220.0 165.0 245.0]


In [86]:
x= dataset[0:15,1:5]
print(x)

[[8.0 90 9 4]
 [7.0 99 9 3]
 [9.0 85 10 5]
 [7.5 86 8 4]
 [8.5 92 8 3]
 [6.0 65 6 2]
 [5.0 73 6 2]
 [5.5 80 6 1]
 [5.0 60 6 2]
 [4.5 62 6 2]
 [2.0 45 2 1]
 [3.0 35 2 1]
 [2.5 33 1 1]
 [1.0 46 1 0]
 [2.0 58 2 0]]


In [87]:
def eucledianDistance(x1,x2):
    distance = (x1[0]-x2[0])**2+(x1[1]-x2[1])**2+(x1[2]-x2[2])**2+(x1[3]-x2[3])**2
    distance = distance ** 0.5
    return distance
    # x1 is a array with 4 values [study hours , attendance, assignment, research papers]

In [88]:
x_test = [6, 90, 5, 4]

In [89]:
distances = []

for i in x:
    d=eucledianDistance(i,x_test)
    distances.append(d)

print(distances)

[4.47213595499958, 9.9498743710662, 7.745966692414834, 5.220153254455275, 4.5, 25.099800796022265, 17.175564037317667, 10.5, 30.099833886584822, 28.129166358070407, 45.37620521815371, 55.24490926773253, 57.325823151525704, 44.64302857109943, 32.63433774416144]


In [90]:
minDistanceIndices = np.argsort(distances)
print(minDistanceIndices)

[ 0  4  3  2  1  7  6  5  9  8 14 13 10 11 12]


In [91]:
k = 3
minDistanceIndices=minDistanceIndices[0:k]
print(minDistanceIndices)

[0 4 3]


In [92]:
# First Method To Find The Average
sum = 0
for i in minDistanceIndices:
    print(y[i])
    sum+=y[i]

print(sum)
average  = sum/k
print(average)

850.0
792.5
802.5
2445.0
815.0


In [93]:
# Second Method To Find The Average
closestMarks=y[minDistanceIndices]
averageMarks = np.average(closestMarks)
print(averageMarks)

815.0


In [94]:
def applyKNN(x_test):
    distances = []
    for i in x:
        d=eucledianDistance(i,x_test)
        distances.append(d)
    #print(distances)
    minDistanceIndices = np.argsort(distances)
    minDistanceIndices=minDistanceIndices[0:k]
    #print(minDistanceIndices)
    closestMarks=y[minDistanceIndices]
    averageMarks = np.average(closestMarks)
    return averageMarks

In [95]:
x_test = [6, 90, 5, 4]
result = applyKNN(x_test)
print(result)

815.0


In [96]:
dataset2 = '/content/drive/MyDrive/Class Contents/5. Summer 2024/AI Lab/Class Materials For The Students/Week 6/dataset2.xlsx'

In [98]:
testDataFrame = pd.read_excel(dataset2)
print(testDataFrame)

   SN  Study Hours  Attendance  Home Works Done  Papers Read  Total Marks  \
0   1          4.0          60                6            4        600.0   
1   2          7.0           2                9            0        405.0   
2   3          2.0          45                5            1        337.5   
3   4          7.5          86                8            4        802.5   

    Level  
0  Medium  
1     Low  
2     Low  
3    High  


In [100]:
testDataset = testDataFrame.to_numpy()
print(testDataset)

[[1 4.0 60 6 4 600.0 'Medium']
 [2 7.0 2 9 0 405.0 'Low']
 [3 2.0 45 5 1 337.5 'Low']
 [4 7.5 86 8 4 802.5 'High']]


In [105]:
x_test = testDataset[:,1:5]
print(x_test)

[[4.0 60 6 4]
 [7.0 2 9 0]
 [2.0 45 5 1]
 [7.5 86 8 4]]


In [106]:
y_test = testDataset[:,5]
print(y_test)

[600.0 405.0 337.5 802.5]


In [110]:
predictions = []
for i in x_test:
    prediction = applyKNN(i)
    predictions.append(prediction)

print(predictions)

[535.0, 248.33333333333334, 230.0, 863.3333333333334]


In [111]:
print('Predictions:')
print(predictions)
print('Actual Values:')
print(y_test)

Predictions:
[535.0, 248.33333333333334, 230.0, 863.3333333333334]
Actual Values:
[600.0 405.0 337.5 802.5]


In [114]:
errors=[]
for i in range(4):
    #print(predictions[i])
    #print(y_test[i])
    error = abs(predictions[i]-y_test[i])/(y_test[i])*100
    errors.append(error)

In [116]:
print('Predictions:')
print(predictions)
print('Actual Values:')
print(y_test)
print("Errors")
print(errors)
print("Average Error")
print(np.average(errors))

Predictions:
[535.0, 248.33333333333334, 230.0, 863.3333333333334]
Actual Values:
[600.0 405.0 337.5 802.5]
Errors
[10.833333333333334, 38.68312757201646, 31.851851851851855, 7.580477673935622]
Average Error
22.237197607784317
