In [24]:
import numpy as np
import pandas as pd

In [25]:
dataset1Link = '/content/drive/MyDrive/Class Contents/5. Summer 2024/AI Lab/Class Materials For The Students/Week 6/dataset1.xlsx'

In [26]:
dataframe = pd.read_excel(dataset1Link)
print(dataframe)

    SN  Study Hours  Attendance  Home Works Done  Papers Read  Total Marks  \
0    1          8.0          90                9            4        850.0   
1    2          7.0          99                9            3        797.5   
2    3          9.0          85               10            5        937.5   
3    4          7.5          86                8            4        802.5   
4    5          8.5          92                8            3        792.5   
5    6          6.0          65                6            2        562.5   
6    7          5.0          73                6            2        557.5   
7    8          5.5          80                6            1        537.5   
8    9          5.0          60                6            2        525.0   
9   10          4.5          62                6            2        517.5   
10  11          2.0          45                2            1        262.5   
11  12          3.0          35                2            1   

In [27]:
dataset = dataframe.to_numpy()

In [28]:
print(dataset)

[[1 8.0 90 9 4 850.0 'High']
 [2 7.0 99 9 3 797.5 'High']
 [3 9.0 85 10 5 937.5 'High']
 [4 7.5 86 8 4 802.5 'High']
 [5 8.5 92 8 3 792.5 'High']
 [6 6.0 65 6 2 562.5 'Medium']
 [7 5.0 73 6 2 557.5 'Medium']
 [8 5.5 80 6 1 537.5 'Medium']
 [9 5.0 60 6 2 525.0 'Medium']
 [10 4.5 62 6 2 517.5 'Medium']
 [11 2.0 45 2 1 262.5 'Low']
 [12 3.0 35 2 1 262.5 'Low']
 [13 2.5 33 1 1 220.0 'Low']
 [14 1.0 46 1 0 165.0 'Low']
 [15 2.0 58 2 0 245.0 'Low']]


In [29]:
y = dataset[0:15,6]
print(y)

['High' 'High' 'High' 'High' 'High' 'Medium' 'Medium' 'Medium' 'Medium'
 'Medium' 'Low' 'Low' 'Low' 'Low' 'Low']


In [30]:
x= dataset[0:15,1:5]
print(x)

[[8.0 90 9 4]
 [7.0 99 9 3]
 [9.0 85 10 5]
 [7.5 86 8 4]
 [8.5 92 8 3]
 [6.0 65 6 2]
 [5.0 73 6 2]
 [5.5 80 6 1]
 [5.0 60 6 2]
 [4.5 62 6 2]
 [2.0 45 2 1]
 [3.0 35 2 1]
 [2.5 33 1 1]
 [1.0 46 1 0]
 [2.0 58 2 0]]


In [31]:
def eucledianDistance(x1,x2):
    distance = (x1[0]-x2[0])**2+(x1[1]-x2[1])**2+(x1[2]-x2[2])**2+(x1[3]-x2[3])**2
    distance = distance ** 0.5
    return distance
    # x1 is a array with 4 values [study hours , attendance, assignment, research papers]

In [32]:
x_test = [2, 20, 1, 1]

In [33]:
distances = []

for i in x:
    d=eucledianDistance(i,x_test)
    distances.append(d)

print(distances)

[70.77428911688199, 79.58643100428615, 66.11353870426238, 66.66520831738246, 72.65844754741185, 45.46427168667722, 53.32916650389353, 60.309617806781034, 40.43513323831146, 42.38218965556169, 25.019992006393608, 15.066519173319364, 13.009611831257688, 26.038433132583073, 38.02630668366309]


In [34]:
minDistanceIndices = np.argsort(distances)
print(minDistanceIndices)

[12 11 10 13 14  8  9  5  6  7  2  3  0  4  1]


In [35]:
k = 3
minDistanceIndices=minDistanceIndices[0:k]
print(minDistanceIndices)

[12 11 10]


In [36]:
poll = dict()
poll['High']=0
poll['Medium']=0
poll['Low']=0



for i in minDistanceIndices:
    label = y[i] # high, low, medium
    poll[label]=poll[label]+1


In [37]:
if(poll['High']>poll['Medium'] and poll['High']>poll['Low']):
    print('high')
elif(poll['Medium']>poll['High'] and poll['Medium']>poll['Low']):
    print('Medium')
else:
    print('Low')

Low


In [40]:
def applyKNN(x_test):
    distances = []

    for i in x:
        d=eucledianDistance(i,x_test)
        distances.append(d)
    minDistanceIndices = np.argsort(distances)
    poll = dict()
    poll['High']=0
    poll['Medium']=0
    poll['Low']=0

    # voting
    for i in minDistanceIndices:
      label = y[i] # high, low, medium
      poll[label]=poll[label]+1

    if(poll['High']>poll['Medium'] and poll['High']>poll['Low']):
      return 'High'
    elif(poll['Medium']>poll['High'] and poll['Medium']>poll['Low']):
      return 'Medium'
    else:
      return 'Low'

In [41]:
x_test = [6, 90, 5, 4]
result = applyKNN(x_test)
print(result)

Low


In [42]:
dataset2 = '/content/drive/MyDrive/Class Contents/5. Summer 2024/AI Lab/Class Materials For The Students/Week 6/dataset2.xlsx'

In [43]:
testDataFrame = pd.read_excel(dataset2)
print(testDataFrame)

   SN  Study Hours  Attendance  Home Works Done  Papers Read  Total Marks  \
0   1          4.0          60                6            4        600.0   
1   2          7.0           2                9            0        405.0   
2   3          2.0          45                5            1        337.5   
3   4          7.5          86                8            4        802.5   

    Level  
0  Medium  
1     Low  
2     Low  
3    High  


In [44]:
testDataset = testDataFrame.to_numpy()
print(testDataset)

[[1 4.0 60 6 4 600.0 'Medium']
 [2 7.0 2 9 0 405.0 'Low']
 [3 2.0 45 5 1 337.5 'Low']
 [4 7.5 86 8 4 802.5 'High']]


In [45]:
x_test = testDataset[:,1:5]
print(x_test)

[[4.0 60 6 4]
 [7.0 2 9 0]
 [2.0 45 5 1]
 [7.5 86 8 4]]


In [47]:
y_test = testDataset[:,6]
print(y_test)

['Medium' 'Low' 'Low' 'High']


In [48]:
predictions = []
for i in x_test:
    prediction = applyKNN(i)
    predictions.append(prediction)

print(predictions)

['Low', 'Low', 'Low', 'Low']


In [49]:
print('Predictions:')
print(predictions)
print('Actual Values:')
print(y_test)

Predictions:
['Low', 'Low', 'Low', 'Low']
Actual Values:
['Medium' 'Low' 'Low' 'High']


In [50]:
correctPredictions = 0

for i in range(4):
    if(predictions[i]==y_test[i]):
        correctPredictions=correctPredictions+1
    else:
        correctPredictions=correctPredictions+0

In [51]:
print(correctPredictions)

2


In [53]:
accuracy = correctPredictions/4*100
print(accuracy)

50.0
