In [3]:
import numpy as np
import pandas as pd

In [4]:
datapath = 'dataset1.xlsx'

In [5]:
dataFrame = pd.read_excel(datapath)

In [6]:
print(dataFrame)

    SN  Study Hours  Attendance  Home Works Done  Papers Read  Total Marks  \
0    1          8.0          90                9            4        850.0   
1    2          7.0          99                9            3        797.5   
2    3          9.0          85               10            5        937.5   
3    4          7.5          86                8            4        802.5   
4    5          8.5          92                8            3        792.5   
5    6          6.0          65                6            2        562.5   
6    7          5.0          73                6            2        557.5   
7    8          5.5          80                6            1        537.5   
8    9          5.0          60                6            2        525.0   
9   10          4.5          62                6            2        517.5   
10  11          2.0          45                2            1        262.5   
11  12          3.0          35                2            1   

In [7]:
dataSet = dataFrame.to_numpy()

In [8]:
print(dataSet)

[[1 8.0 90 9 4 850.0 'High']
 [2 7.0 99 9 3 797.5 'High']
 [3 9.0 85 10 5 937.5 'High']
 [4 7.5 86 8 4 802.5 'High']
 [5 8.5 92 8 3 792.5 'High']
 [6 6.0 65 6 2 562.5 'Medium']
 [7 5.0 73 6 2 557.5 'Medium']
 [8 5.5 80 6 1 537.5 'Medium']
 [9 5.0 60 6 2 525.0 'Medium']
 [10 4.5 62 6 2 517.5 'Medium']
 [11 2.0 45 2 1 262.5 'Low']
 [12 3.0 35 2 1 262.5 'Low']
 [13 2.5 33 1 1 220.0 'Low']
 [14 1.0 46 1 0 165.0 'Low']
 [15 2.0 58 2 0 245.0 'Low']]


In [9]:
total_rows = 0
for i in dataSet:
    total_rows += 1

print(total_rows)

total_cols = 0
for i in dataSet[0]:
    total_cols += 1

print(total_cols)

15
7


In [10]:
x_axix = dataSet[0:total_rows, 0:total_cols-2]
print(x_axix)

[[1 8.0 90 9 4]
 [2 7.0 99 9 3]
 [3 9.0 85 10 5]
 [4 7.5 86 8 4]
 [5 8.5 92 8 3]
 [6 6.0 65 6 2]
 [7 5.0 73 6 2]
 [8 5.5 80 6 1]
 [9 5.0 60 6 2]
 [10 4.5 62 6 2]
 [11 2.0 45 2 1]
 [12 3.0 35 2 1]
 [13 2.5 33 1 1]
 [14 1.0 46 1 0]
 [15 2.0 58 2 0]]


In [11]:
y_axis = dataSet[0:total_rows, total_cols-2]
print(y_axis)

[850.0 797.5 937.5 802.5 792.5 562.5 557.5 537.5 525.0 517.5 262.5 262.5
 220.0 165.0 245.0]


In [12]:
def eucledianDistance(x1, x2):
    # study hours, attendance, assignments, research papers
    #           1,          2,           3,               4
    distance = (x1[1]-x2[0])**2 + (x1[2]-x2[1])**2 + (x1[3]-x2[2])**2 + (x1[4]-x2[3])**2
    distance = distance**0.5 
    return distance

In [13]:
x_test = np.array([6, 90, 5, 4])
eucledianDistance(x_axix[0], x_test)

4.47213595499958

In [14]:
def applyKNN(input_data):
    distances = []
    for i in x_axix:
        d = eucledianDistance(i, input_data)
        distances.append(d)
    
    distances = np.array(distances)

    k = 3
    sortedDistancesIndex = np.argsort(distances)
    sortedDistancesIndex = sortedDistancesIndex[0:k]
    # print(sortedDistancesIndex)


    avg = 0
    for i in sortedDistancesIndex:
        avg += y_axis[i]
    
    avg /= k
    return avg


In [15]:
applyKNN(x_test)

815.0