In [188]:
import numpy as np
import pandas as pd

In [194]:
datapath = 'dataset2.xlsx'

In [189]:
dataFrame = pd.read_excel(datapath)

In [195]:
print(dataFrame)

   SN  Study Hours  Attendance  Home Works Done  Papers Read  Total Marks  \
0   1          4.0          60                6            4        600.0   
1   2          7.0           2                9            0        405.0   
2   3          2.0          45                5            1        337.5   
3   4          7.5          86                8            4        802.5   

    Level  
0  Medium  
1     Low  
2     Low  
3    High  


In [191]:
dataSet = dataFrame.to_numpy()

In [190]:
print(dataSet)

[[1 4.0 60 6 4 600.0 'Medium']
 [2 7.0 2 9 0 405.0 'Low']
 [3 2.0 45 5 1 337.5 'Low']
 [4 7.5 86 8 4 802.5 'High']]


In [193]:
total_rows = 0
for i in dataSet:
    total_rows += 1

print(total_rows)

total_cols = 0
for i in dataSet[0]:
    total_cols += 1

print(total_cols)

4
7


In [192]:
x_axix = dataSet[0:total_rows, 1:5]
print(x_axix)

[[4.0 60 6 4]
 [7.0 2 9 0]
 [2.0 45 5 1]
 [7.5 86 8 4]]


In [200]:
y_axis = dataSet[0:total_rows, total_cols-2]
print(y_axis)

[600.0 405.0 337.5 802.5]


In [198]:
def eucledianDistance(x1, x2):
    # study hours, attendance, assignments, research papers
    #           1,          2,           3,               4
    distance = (x1[0]-x2[0])**2 + (x1[1]-x2[1])**2 + (x1[2]-x2[2])**2 + (x1[3]-x2[3])**2
    distance = distance**0.5 
    return distance

In [196]:
x_test = np.array([6, 90, 5, 4])
eucledianDistance(x_axix[0], x_test)

30.083217912982647

In [197]:
def applyKNN(input_data):
    distances = []
    for i in x_axix:
        d = eucledianDistance(i, input_data)
        distances.append(d)
    
    distances = np.array(distances)

    k = 3
    sortedDistancesIndex = np.argsort(distances)
    sortedDistancesIndex = sortedDistancesIndex[0:k]
    # print(sortedDistancesIndex)


    avg = 0
    for i in sortedDistancesIndex:
        avg += y_axis[i]
    
    avg /= k
    return avg


In [199]:
actual_values = y_axis
predicted_vaules = []

for x in x_axix:
    # print(x)
    val = applyKNN(x)
    predicted_vaules.append(val)
    # print(val)

print(actual_values)
print(predicted_vaules)

[600.0 405.0 337.5 802.5]
[580.0, 447.5, 580.0, 580.0]
