In [3]:
import numpy as np
import copy


class State:
    # board
    # parent
    # g
    # h
    def __init__(self, board=None): # must be a numpy board

        if board == None:
            #print('here')
            boardUsingList = [
                              [7,2,4],
                              [5,0,6],
                              [8,3,1]
                            ]
            self.board = np.array(boardUsingList)
        else:
            self.board=board

        self.g=0
        self.h=0
        self.parent=None

    def printState(self):
        print("*******************")
        print(self.board)
        print("*******************")


    def moveUp(self):
        child = copy.deepcopy(self)
        r0,c0 = np.where(self.board==0)
        r0=r0[0]
        c0=c0[0]
        # print(r0)
        # print(c0)
        # print(self.board[r0][c0])

        rOther=r0-1
        cOther=c0

        if(rOther<0):
            return child

        child.board [r0][c0] = child.board [rOther][cOther]
        child.board [rOther][cOther] = 0
        #print('here')
        return child




    def moveDown(self):
        child = copy.deepcopy(self)
        r0,c0 = np.where(self.board==0)
        r0=r0[0]
        c0=c0[0]
        # print(r0)
        # print(c0)
        # print(self.board[r0][c0])

        rOther=r0+1
        cOther=c0

        if(rOther>2):
            return child

        child.board [r0][c0] = child.board [rOther][cOther]
        child.board [rOther][cOther] = 0
        #print('Here')
        return child

    def moveLeft(self):
        child = copy.deepcopy(self)
        r0,c0 = np.where(self.board==0)
        r0=r0[0]
        c0=c0[0]
        # print(r0)
        # print(c0)
        # print(self.board[r0][c0])

        rOther=r0
        cOther=c0-1

        #print(rOther)
        #print(cOther)

        if(cOther<0):
            #print('debug')
            return child

        child.board [r0][c0] = child.board [rOther][cOther]
        child.board [rOther][cOther] = 0
        #print('Here')
        return child


    def moveRight(self):
        child = copy.deepcopy(self)
        r0,c0 = np.where(self.board==0)
        r0=r0[0]
        c0=c0[0]
        # print(r0)
        # print(c0)
        # print(self.board[r0][c0])

        rOther=r0
        cOther=c0+1

        if(cOther>2):

            return child

        child.board [r0][c0] = child.board [rOther][cOther]
        child.board [rOther][cOther] = 0

        return child

    def __eq__(self,otherNode):
        if(otherNode==None):
            return False
        if(np.array_equal(self.board,otherNode.board)):
            return True
        else:
            return False
    def __hash__(self):
        return 1

In [4]:
state = State()
state.printState()

*******************
[[7 2 4]
 [5 0 6]
 [8 3 1]]
*******************


In [5]:
child1 = state.moveUp()
child1.printState()
child1 = state.moveDown()
child1.printState()
child1 = state.moveLeft()
child1.printState()
child1 = state.moveRight()
child1.printState()

*******************
[[7 0 4]
 [5 2 6]
 [8 3 1]]
*******************
*******************
[[7 2 4]
 [5 3 6]
 [8 0 1]]
*******************
*******************
[[7 2 4]
 [0 5 6]
 [8 3 1]]
*******************
*******************
[[7 2 4]
 [5 6 0]
 [8 3 1]]
*******************


In [6]:
def goalTest(node):
      goalBoardUsingList = [
                    [0,1,2],
                    [3,4,5],
                    [6,7,8]
                  ]
      goalBoard = np.array(goalBoardUsingList)

      if np.array_equal(node.board,goalBoard):
          return True
      else:
          return False

In [ ]:
goalTest(state)

False

In [7]:
def calculateHeuristics(node):
      goalBoardUsingList = [
                    [0,1,2],
                    [3,4,5],
                    [6,7,8]
                  ]
      goalBoard = np.array(goalBoardUsingList)

      totalDistance = 0
      for i in range(1,9):
          ri,ci = np.where(node.board==i)
          ri=ri[0]
          ci=ci[0]

          rg,cg = np.where(goalBoard==i)
          rg=rg[0]
          cg=cg[0]

          dist = abs(ri-rg)+abs(ci-cg)
          totalDistance +=dist

      return totalDistance

In [8]:
state = State()
calculateHeuristics(state)

18

In [9]:
def sumOfGandH(node):
  return node.h-node.g

In [10]:
def a_star_search (initialNode):
    if goalTest(initialNode):
        return initialNode

    frontier = list() # queue
    explored = set()


    initialNode.g=0
    initialNode.h=calculateHeuristics(initialNode)
    frontier.append(initialNode)

    while True:
        if (len(frontier)==0):
            return None

        frontier.sort(key=sumOfGandH)
        node = frontier.pop(0)
        explored.add(node)
        print(len(frontier))

        actions = [node.moveUp,node.moveDown,node.moveLeft,node.moveRight]

        for action in actions:
            child = action()
            child.g=node.g+50
            child.h=calculateHeuristics(child)
            child.parent=node
            if (child not in frontier) and (child not in explored):
                if(goalTest(child)):
                    return child
                frontier.append(child)
            elif child in frontier:
                 indexOfChildInFrontier = frontier.index(child)
                 childInFrontier = frontier[indexOfChildInFrontier]
                 if(child.g+child.h<childInFrontier.g+childInFrontier.h):
                      frontier[indexOfChildInFrontier]=child
                      frontier.sort(key=sumOfGandH)

In [11]:
state = State()
result = a_star_search(state)


0
3
4
4
5
5
6
6
7
7
8
8
9
11
12
12
13
13
14
16
17
17
18
18
19
19
20
22
23
23
24
24
25
27
28
28
29
29
30
30
31
31
32
32
33
35
36
36
37
37
38
38
39
41
42
42
43
45
46
46
47
47
48
48
49
49
50
52
53
53
54
54
55
55
56
56
57
59
60
60
61
61
62
62
63
63
64
66
67
67
68
68
69
71
72
72
73
73
74
76
77
77
78
78
79
81
82
82
83
85
86
86
86
86
87
87
88
88
89
89
90
92
93
93
94
94
95
97
98
98
99
101
102
102
103
103
104
106
107
107
108
110
111
111
112
112
113
115
116
116
117
117
118
120
121
121
122
122
123
125
126
126
127
127
128
130
131
131
132
131
133
134
134
135
135
136
138
139
139
139
139
140
142
143
143
143
143
144
144
145
147
148
148
149
149
150
150
151
153
154
153
153
154
154
155
157
158
158
159
159
160
160
161
161


In [12]:
def printSolution(state):
    if(state==None):
      return
    else:
      printSolution(state.parent)
      state.printState()

In [13]:
printSolution(result)

*******************
[[7 2 4]
 [5 0 6]
 [8 3 1]]
*******************
*******************
[[7 2 4]
 [5 3 6]
 [8 0 1]]
*******************
*******************
[[7 2 4]
 [5 3 6]
 [0 8 1]]
*******************
*******************
[[7 2 4]
 [0 3 6]
 [5 8 1]]
*******************
*******************
[[0 2 4]
 [7 3 6]
 [5 8 1]]
*******************
*******************
[[2 0 4]
 [7 3 6]
 [5 8 1]]
*******************
*******************
[[2 4 0]
 [7 3 6]
 [5 8 1]]
*******************
*******************
[[2 4 6]
 [7 3 0]
 [5 8 1]]
*******************
*******************
[[2 4 6]
 [7 3 1]
 [5 8 0]]
*******************
*******************
[[2 4 6]
 [7 3 1]
 [5 0 8]]
*******************
*******************
[[2 4 6]
 [7 3 1]
 [0 5 8]]
*******************
*******************
[[2 4 6]
 [0 3 1]
 [7 5 8]]
*******************
*******************
[[2 4 6]
 [3 0 1]
 [7 5 8]]
*******************
*******************
[[2 0 6]
 [3 4 1]
 [7 5 8]]
*******************
*******************
[[0 2 6]
 [3 4 1]
 [7 5 8]]
