In [66]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [67]:
df = pd.read_excel('logistic_regression_dataset.xlsx')
print(df)

     Feature_1  Feature_2  Feature_3  Output
0     0.496714  -0.138264   0.647689       1
1     1.523030  -0.234153  -0.234137       1
2     1.579213   0.767435  -0.469474       1
3     0.542560  -0.463418  -0.465730       1
4     0.241962  -1.913280  -1.724918       1
..         ...        ...        ...     ...
495   0.932591  -1.418366  -1.760809       1
496  -1.525656   1.262584  -0.551858       0
497   2.558199  -0.564248   0.184551       1
498   1.542110   2.006093   2.061504       1
499   1.208366   1.024063   0.592527       1

[500 rows x 4 columns]


In [68]:
dataset = df.to_numpy()

normalized_data = np.zeros_like(dataset)
noOfColumns = dataset.shape[1]

for i in range(noOfColumns):
    min_val = np.min(dataset[:, i])
    max_val = np.max(dataset[:, i])
    normalized_data[:, i] = (dataset[:, i] - min_val) / (max_val - min_val)

print(normalized_data)

[[0.61961128 0.49096998 0.52172633 1.        ]
 [0.80703318 0.47579802 0.39013561 1.        ]
 [0.8172931  0.63427343 0.3550173  1.        ]
 ...
 [0.99607192 0.42356914 0.45261451 1.        ]
 [0.81051752 0.83025905 0.73270338 1.        ]
 [0.7495705  0.67487815 0.51349482 1.        ]]


In [69]:
X = normalized_data[:, 0:3]
Y = normalized_data[:, 3].reshape(-1, 1)  # Reshape Y to be (n, 1)

print(X)
print(Y)

[[0.61961128 0.49096998 0.52172633]
 [0.80703318 0.47579802 0.39013561]
 [0.8172931  0.63427343 0.3550173 ]
 ...
 [0.99607192 0.42356914 0.45261451]
 [0.81051752 0.83025905 0.73270338]
 [0.7495705  0.67487815 0.51349482]]
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.

In [70]:
def sigmoid(z):
    return 1 / (1 + tf.exp(-z))

def lossFunction(yPred, yReal):
    return -tf.reduce_mean(yReal * tf.math.log(yPred) + (1 - yReal) * tf.math.log(1 - yPred))


In [71]:
X_tensor = tf.Variable(X, dtype=tf.float64)
Y_tensor = tf.Variable(Y, dtype=tf.float64)

# initial weights and bias
W_tensor = tf.Variable(np.random.randn(3, 1), dtype=tf.float64)
b_tensor = tf.Variable(np.random.randn(1, 1), dtype=tf.float64)

learning_rate = 0.001
epochs = 10000

In [72]:
# solution of ques 1
for i in range(epochs):
    with tf.GradientTape(persistent=True) as tape:
        Z = tf.matmul(X_tensor, W_tensor) + b_tensor
        YPred = sigmoid(Z)
        loss = lossFunction(YPred, Y_tensor)

    dlossBydW = tape.gradient(loss, W_tensor)
    dlossBydb = tape.gradient(loss, b_tensor)

    W_tensor.assign_sub(learning_rate * dlossBydW)
    b_tensor.assign_sub(learning_rate * dlossBydb)
    print(f'Epoch {i + 1}, Loss: {loss.numpy()}')

print(W_tensor.numpy())
print(b_tensor.numpy())


Epoch 1, Loss: 1.190724873620237
Epoch 2, Loss: 1.1904324180313262
Epoch 3, Loss: 1.1901400501790194
Epoch 4, Loss: 1.1898477700868653
Epoch 5, Loss: 1.1895555777783868
Epoch 6, Loss: 1.1892634732770848
Epoch 7, Loss: 1.188971456606434
Epoch 8, Loss: 1.1886795277898863
Epoch 9, Loss: 1.1883876868508692
Epoch 10, Loss: 1.1880959338127863
Epoch 11, Loss: 1.1878042686990167
Epoch 12, Loss: 1.1875126915329146
Epoch 13, Loss: 1.187221202337811
Epoch 14, Loss: 1.186929801137012
Epoch 15, Loss: 1.1866384879538
Epoch 16, Loss: 1.1863472628114322
Epoch 17, Loss: 1.186056125733142
Epoch 18, Loss: 1.1857650767421377
Epoch 19, Loss: 1.185474115861605
Epoch 20, Loss: 1.1851832431147018
Epoch 21, Loss: 1.1848924585245653
Epoch 22, Loss: 1.184601762114305
Epoch 23, Loss: 1.184311153907008
Epoch 24, Loss: 1.1840206339257353
Epoch 25, Loss: 1.1837302021935243
Epoch 26, Loss: 1.1834398587333874
Epoch 27, Loss: 1.183149603568312
Epoch 28, Loss: 1.1828594367212608
Epoch 29, Loss: 1.1825693582151722
Epoch 

In [73]:
X_test = X[0:200, ]
Y_test = Y[0:200, ]

X_test_tensor = tf.Variable(X_test, dtype=tf.float64)
Y_test_tensor = tf.Variable(Y_test, dtype=tf.float64)

In [74]:
Z_test = tf.matmul(X_test_tensor, W_tensor) + b_tensor
YPred_test = sigmoid(Z_test)
YPred_binary = (YPred_test.numpy() >= 0.5).astype(int)

In [75]:
# solution of ques 2
accuracy = np.mean(YPred_binary == Y_test_tensor.numpy())

true_positive = np.sum((YPred_binary == 1) & (Y_test_tensor.numpy() == 1))
predicted_positive = np.sum(YPred_binary == 1)
precision = true_positive / predicted_positive if predicted_positive > 0 else 0

actual_positive = np.sum(Y_test_tensor.numpy() == 1)
recall = true_positive / actual_positive if actual_positive > 0 else 0

f1_score = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0

print(f'accuracy: {accuracy}')
print(f'precision: {precision}')
print(f'recall: {recall}')
print(f'f1 score: {f1_score}')

accuracy: 0.86
precision: 0.8181818181818182
recall: 0.9183673469387755
f1 score: 0.8653846153846154
