In [23]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [24]:
df = pd.read_csv("House_Rent_Dataset.csv")
print(df)

    Size (sq meters)  Number of rooms  Distance to city center (km)  \
0          74.908024                1                     14.704322   
1         190.142861                4                      4.181432   
2         146.398788                5                     10.828959   
3         119.731697                4                     13.915688   
4          31.203728                5                      4.571000   
..               ...              ...                           ...   
95         98.759119                1                     12.557888   
96        104.546566                2                      3.885479   
97         85.508204                1                      1.418818   
98          5.083825                3                      7.935677   
99         21.578285                4                      1.015371   

           Rent  
0   1673.089398  
1   4561.060306  
2   3559.679586  
3   3015.546079  
4   1385.856243  
..          ...  
95  2298.804680  
96 

In [25]:
dataset = df.to_numpy()
import numpy as np
# Create an empty array to store the normalized data
normalized_data = np.zeros_like(dataset)

# determine the number of columns
noOfColumns = dataset.shape[1]

# Normalize one column at a time using aloop
for i in range(noOfColumns):
    min_val = np.min(dataset[:, i])
    max_val = np.max(dataset[:, i])
    normalized_data[:, i] = (dataset[:, i] - min_val) / (max_val - min_val)


# print normalized data
print(normalized_data)
dataset=normalized_data

[[0.3760253  0.         0.73661004 0.2885856 ]
 [0.96314049 0.75       0.20572411 1.        ]
 [0.74026683 1.         0.54109573 0.75332277]
 [0.60439946 0.75       0.69682298 0.61928249]
 [0.15335431 1.         0.22537805 0.21782941]
 [0.15332973 1.         0.17129997 0.22033619]
 [0.05355959 0.5        0.98578771 0.03745289]
 [0.87699703 1.         0.51606004 0.87838373]
 [0.60690263 0.75       0.25794809 0.64023783]
 [0.71589122 1.         1.         0.7158334 ]
 [0.0153484  0.5        0.96888778 0.01187134]
 [0.98270054 0.5        0.55809301 0.95057458]
 [0.84262295 0.75       0.88535876 0.82102548]
 [0.21074425 0.25       0.18517608 0.18363732]
 [0.17965067 0.25       0.27615286 0.15560315]
 [0.18126021 1.         0.70143762 0.22492538]
 [0.30439254 0.         0.84905937 0.21693885]
 [0.52909408 1.         0.8588096  0.52387239]
 [0.43452027 0.75       0.40292182 0.44400254]
 [0.29113233 0.75       0.89053878 0.30244783]
 [0.61784442 0.75       0.85336513 0.63178271]
 [0.13651574 

In [26]:

X=dataset[:,0:3]
print(X)
Y=dataset[:,3]
Y=Y.reshape(Y.shape[0],1) # making it a (rows x 1) eg: 3x1 matrix (2D array)
print(Y)

[[0.3760253  0.         0.73661004]
 [0.96314049 0.75       0.20572411]
 [0.74026683 1.         0.54109573]
 [0.60439946 0.75       0.69682298]
 [0.15335431 1.         0.22537805]
 [0.15332973 1.         0.17129997]
 [0.05355959 0.5        0.98578771]
 [0.87699703 1.         0.51606004]
 [0.60690263 0.75       0.25794809]
 [0.71589122 1.         1.        ]
 [0.0153484  0.5        0.96888778]
 [0.98270054 0.5        0.55809301]
 [0.84262295 0.75       0.88535876]
 [0.21074425 0.25       0.18517608]
 [0.17965067 0.25       0.27615286]
 [0.18126021 1.         0.70143762]
 [0.30439254 0.         0.84905937]
 [0.52909408 1.         0.8588096 ]
 [0.43452027 0.75       0.40292182]
 [0.29113233 0.75       0.89053878]
 [0.61784442 0.75       0.85336513]
 [0.13651574 0.75       0.93883502]
 [0.29206522 0.75       0.78718628]
 [0.36769173 0.5        0.66978535]
 [0.45910334 0.25       0.58068798]
 [0.79445873 0.75       0.37040606]
 [0.19783842 0.         0.94337401]
 [0.51837228 0.         0.97

In [27]:
def lossFunction(yPred,yReal):
    return tf.reduce_mean(((yPred-yReal)**2))

In [28]:
X_tensor = tf.Variable(X)
Y_tensor = tf.Variable(Y)

print(f'X_tensor shape = {X_tensor.shape}')
print(f'Y_tensor shape = {Y_tensor.shape}')

W_tensor = tf.Variable(np.random.randn(3, 1), dtype=tf.double)
print(f'W_tensor shape = {W_tensor.shape}')
b_tensor = tf.Variable(np.random.randn(1,1), dtype=tf.double)
print(f'b_tensor shape = {b_tensor.shape}')
learning_rate = 0.001
epochs=10000


X_tensor shape = (100, 3)
Y_tensor shape = (100, 1)
W_tensor shape = (3, 1)
b_tensor shape = (1, 1)


In [29]:
for i in range(epochs):
  with tf.GradientTape(persistent=True) as tape:
      YPred= tf.matmul(X_tensor,W_tensor)+b_tensor
      loss = lossFunction(YPred,Y_tensor)

  dlossBydW = tape.gradient(loss,W_tensor)
  dlossBydb = tape.gradient(loss,b_tensor)

  W_tensor.assign_sub(learning_rate*dlossBydW)
  b_tensor.assign_sub(learning_rate*dlossBydb)
  print(f"Epoch {i+1}, Loss: {loss.numpy()}")

print(W_tensor.numpy())
print(b_tensor.numpy())

Epoch 1, Loss: 10.917967953546794
Epoch 2, Loss: 10.846380777820329
Epoch 3, Loss: 10.775296603767242
Epoch 4, Loss: 10.704711887298396
Epoch 5, Loss: 10.634623109298781
Epoch 6, Loss: 10.56502677545151
Epoch 7, Loss: 10.495919416063094
Epoch 8, Loss: 10.427297585889901
Epoch 9, Loss: 10.359157863965889
Epoch 10, Loss: 10.291496853431513
Epoch 11, Loss: 10.224311181363866
Epoch 12, Loss: 10.157597498607995
Epoch 13, Loss: 10.091352479609407
Epoch 14, Loss: 10.025572822247785
Epoch 15, Loss: 9.96025524767183
Epoch 16, Loss: 9.895396500135305
Epoch 17, Loss: 9.830993346834218
Epoch 18, Loss: 9.76704257774515
Epoch 19, Loss: 9.703541005464727
Epoch 20, Loss: 9.640485465050226
Epoch 21, Loss: 9.5778728138613
Epoch 22, Loss: 9.515699931402812
Epoch 23, Loss: 9.453963719168796
Epoch 24, Loss: 9.392661100487494
Epoch 25, Loss: 9.331789020367506
Epoch 26, Loss: 9.271344445345003
Epoch 27, Loss: 9.21132436333204
Epoch 28, Loss: 9.151725783465913
Epoch 29, Loss: 9.092545735959606
Epoch 30, Loss: